//
//  ZohoConstants.h
//  iPitch V2
//
//  Created by Satheeshwaran on 3/29/13.
//  Copyright (c) 2013 Cognizant. All rights reserved.
//

#ifndef iPitch_V2_ZohoConstants_h
#define iPitch_V2_ZohoConstants_h



#endif


#define ZOHO_MIDDLEWARE_URL_JSON @"https://crm.zoho.com/crm/private/json"
#define ZOHO_MIDDLEWARE_URL_XML @"https://crm.zoho.com/crm/private/xml"

#define ZOHO_INSERT_NOTE_CALL @"https://crm.zoho.com/crm/private/xml/Events/insertRecords?authtoken=%@&scope=crmapi&xmlData=%@"

#define ZOHO_RESPONSE_PARAMETER @"response"
#define ZOHO_RESULT_PARAMETER @"result"
#define ZOHO_FL_PARAMETER @"FL"
#define ZOHO_ROW_PARAMETER @"row"
#define ZOHO_VALUE_PARAMETER @"val"
#define ZOHO_CONTENT_PARAMETER @"content"
#define ZOHO_ID_PARAMETER @"id"
#define ZOHO_EVENTS_PARAMETER @"Events"
#define ZOHO_NO_PARAMETER @"no"
#define ZOHO_SUBJECT_PARAMETER @"Subject"
#define ZOHO_START_TIME_PARAMETER @"Start DateTime"
#define ZOHO_END_TIME_PARAMETER @"End DateTime"
#define ZOHO_PURPOSE_PARAMETER @"Event Purpose"
#define ZOHO_VENUE_PARAMETER @"Venue"
#define ZOHO_SEID_PARAMETER @"SEID"
#define ZOHO_SEMODULE_PARAMETER @"SEMODULE"
#define ZOHO_ACCOUNTS_PARAMETER @"Accounts"
#define ZOHO_POTENTIALS_PARAMETER @"Potentials"
#define ZOHO_CONTACTS_PARAMETER @"Contacts"
#define ZOHO_CONTACT_ID_PARAMETER @"CONTACTID"

#define ZOHO_POTENTIAL_NAME_PARAMETER @"Potential Name"
#define ZOHO_DESCRIPTION_PARAMETER @"Description"
#define ZOHO_CLOSING_DATE_PARAMETER @"Closing Date"
#define ZOHO_TYPE_PARAMETER @"Type"
#define ZOHO_STAGE_PARAMETER @"Stage"
#define ZOHO_ACCOUNT_ID_PARAMETER @"ACCOUNTID"
#define ZOHO_CONTACT_ID_PARAMETER @"CONTACTID"
#define ZOHO_EMAIL_PARAMETER @"Email"
#define ZOHO_AMOUNT_PARAMETER @"Amount"
#define ZOHO_PROBABILITY_PARAMETER @"Probability"
#define ZOHO_NEXT_STEP_PARAMETER @"Next Step"
#define ZOHO_RECORD_ADDED_SUCCESSFULLY_PARAMETER @"Record(s) added successfull"
#define ZOHO_RECORD_UPDATED_SUCCESSFULLY_PARAMETER @"Record(s) updated successfully"

#define ZOHO_FIRST_NAME_PARAMETER @"First Name"
#define ZOHO_LAST_NAME_PARAMETER @"Last Name"
#define ZOHO_FAX_PARAMETER @"Fax"
#define ZOHO_PHONE_PARAMETER @"Phone"
#define ZOHO_DEPARTMENT_PARAMETER @"Department"
#define ZOHO_MOBILE_PARAMETER @"Mobile"
#define ZOHO_ASSISTANT_PARAMETER @"Assistant"
#define ZOHO_DOB_PARAMETER @"Date of Birth"
#define ZOHO_SKYPE_PARAMETER @"Skype ID"
#define ZOHO_TWITTER_ID_PARAMETER @"Twitter"
#define ZOHO_LINKEDIN_PARAMETER @"Linkedin"
#define ZOHO_MAILING_CITY_PARAMETER @"Mailing City"
#define ZOHO_MAILING_COUNTRY_PARAMETER @"Mailing Country"
#define ZOHO_MAILING_STATE_PARAMETER @"Mailing State"
#define ZOHO_MAILING_STREET_PARAMETER @"Mailing Street"
#define ZOHO_MAILING_ZIP_PARAMETER @"Mailing Zip"
    
#define ZOHO_ACCOUNT_NAME_PARAMETER @"Account Name"
#define ZOHO_ACCOUNT_NUMBER_PARAMETER @"Account Number"
#define ZOHO_ACCOUNT_TYPE_PARAMETER  @"Account Type"
#define ZOHO_ACCOUNT_REVENUE_PARAMETER @"Annual Revenue"
#define ZOHO_ACCOUNT_OWNERSHIP_PARAMETER @"Ownership"
#define ZOHO_ACCOUNT_INDUSTRY_PARAMETER @"Industry"
#define ZOHO_ACCOUNT_PARENT_ID_PARAMETER @"PARENTACCOUNTID"
#define ZOHO_BILLING_STREET_PARAMETER @"Billing Street"
#define ZOHO_BILLING_CITY_PARAMETER @"Billing City"
#define ZOHO_BILLING_STATE_PARAMETER @"Billing State"
#define ZOHO_BILLING_CODE_PARAMETER @"Billing Code"
#define ZOHO_BILLING_COUNTRY_PARAMETER @"Billing Country"
#define ZOHO_WEBSITE_PARAMETER @"Website"

#define ZOHO_EMPLOYESS_PARAMETER @"Employees"

#define ZOHO_LEAD_ID_PARAMETER @"LEADID"
#define ZOHO_SMOWNERID_PARAMETER @"SMOWNERID"
#define ZOHO_LEAD_OWNER_PARAMETER @"Lead Owner"
#define ZOHO_COMPANY_PARAMETER @"Company"
#define ZOHO_DESIGNATION_PARAMETER @"Designation"
#define ZOHO_LEAD_SOURCE_PARAMETER @"Lead Source"
#define ZOHO_INDUSTRY_PARAMETER @"Industry"
#define ZOHO_LEAD_STATUS_PARAMETER @"Lead Status"
#define ZOHO_NUMBER_OF_EMPLOYEES_PARAMETER @"No of Employees"
#define ZOHO_RATING_PARAMETER @"Rating"
#define ZOHO_CAMPAIGN_ID_PARAMETER @"CAMPAIGNID"
#define ZOHO_CAMPAIGN_SOURCE_PARAMETER @"Campaign Source"
#define ZOHO_SMCREATORID_PARAMETER @"SMCREATORID"
#define ZOHO_CREATED_BY_PARAMETER @"Created By"
#define ZOHO_MODIFIED_BY_ID_PARAMETER @"MODIFIEDBY"
#define ZOHO_MODIFIED_BY_PARAMETER @"Modified By"
#define ZOHO_CREATED_TIME_PARAMETER @"Created Time"
#define ZOHO_MODIFIED_TIME_PARAMETER @"Modified Time"

#define ZOHO_STREET_PARAMETER @"Street"
#define ZOHO_FAVOURITE_PARAMETER @"Favourite"
#define ZOHO_SALUTATION_PARAMETER @"Salutation"
#define ZOHO_COUNTRY_PARAMETER @"Country"
#define ZOHO_CITY_PARAMETER @"City"
#define ZOHO_STATE_PARAMETER @"State"
#define ZOHO_ZIP_CODE_PARAMETER @"Zip Code"
#define ZOHO_EMAIL_OPT_OUT_PARAMETER @"Email Opt Out"
#define ZOHO_SECONDARY_EMAIL_PARAMETER @"Secondary Email"
#define ZOHO_LAST_ACTIVITY_TIME @"Last Activity Time"
#define ZOHO_ACTIVITY_ID_PARAMETER @"ACTIVITYID"
#define ZOHO_PURPOSE_TYPE_PARAMETER @"Purpose Type"
#define ZOHO_PURPOSE_TYPE_CALL @"Call"
#define ZOHO_PURPOSE_TYPE_EMAIL @"Email"
#define ZOHO_PURPOSE_TYPE_MEETING @"Meeting"
#define ZOHO_PURPOSE_TYPE_DEMO @"Product Demo"
#define ZOHO_EVENT_TYPE_PARAMETER @"Event Type"
#define ZOHO_RELATED_TO_ID @"RELATEDTOID"
#define ZOHO_CONTACT_NAME_PARAMETER @"Contact Name"
#define ZOHO_RELATED_TO_MODULE_ID @"Related To"
#define ZOHO_RELATED_TO_CONTACT_ID @"Related To Contact ID"
#define ZOHO_RELATED_TO_ACCOUNT_ID @"Related To Account ID"
#define ZOHO_RELATED_TO_OPPORTUNITY_ID @"Related To Opportunity ID"


#define RECORDS_PARAMETER @"records"
#define DONE_PARAMTER @"done"
#define LOCATION_PARAMTER @"Location"
#define ATTRIBUTES_PARAMTER @"attributes"
#define URL_PARAMTER @"url"
#define END_DATE_TIME_PARAMTER @"EndDateTime"
#define START_DATE_PARAMTER @"ActivityDate"
#define START_DATE_TIME_PARARMTER @"ActivityDateTime"
#define ID_PARAMTER @"Id"
#define AUTH_TOKEN_PARAMETER @"access_token"
#define ISSUED_AT_PARAMETER @"issued_at"
#define REFRESH_TOKEN_PARAMTER @"refresh_token"

#define CALL_TYPE_PARAMTER @"CallType"
#define PRIORITY_PARAMTER @"Priority"
#define STATUS_PARAMETER @"Status"

#define TASK_ID_PARMETER @"taskID"
#define TASKS_MODULE @"Tasks"

#define ANNUAL_REVENUE_PARAMETER @"AnnualRevenue"
#define BILLING_CITY_PARARMETER @"BillingCity"
#define BILLING_COUNTRY_PARARMETER @"BillingCountry"
#define BILLING_ZIP_PARARMETER @"BillingPostalCode"
#define BILLING_STATE_PARARMETER @"BillingState"
#define BILLING_STREET_PARARMETER @"BillingStreet"
#define NAME_PARAMETER @"Name"
#define NUMBER_OF_EMPLOYEES @"NumberOfEmployees"
#define PARENT_ID_PARAMETER @"ParentId"
#define SITE_PARAMETER @"Site"
#define ACCOUNT_ID_PARAMTER @"AccountId"

#define MAILING_STREET_PARAMETER @"MailingStreet"
#define BIRTH_DATE_PARAMETER @"Birthdate"
#define FIRST_NAME_PARAMETER @"FirstName"
#define HOME_PHONE_PARAMETER @"HomePhone"
#define LAST_NAME_PARAMTER @"LastName"
#define MAILING_CITY_PARAMETER @"MailingCity"
#define MAILING_COUNTRY_PARAMETER @"MailingCountry"
#define MAILING_POSTAL_CODE @"MailingPostalCode"
#define MAILING_STATE_PARAMETER @"MailingState"
#define MAILING_STREET_PARAMETER @"MailingStreet"
#define MOBILE_PHONE_PARAMETER @"MobilePhone"
#define TITLE_PARAMETER @"Title"
#define CONTACT_ID_PARAMETER @"ContactID"

#define ERROR_PARAMETER @"error"
#define INVALID_GRANT_PARAMETER @"invalid_grant"
#define ERROR_DESCRIPTION_PARAMETER @"error_description" 
#define EXPIRED_TOKEN_PARAMETER @"expired access/refresh token"
#define TOKEN_EXPIRED_NOTIFICATION @"OAuthTokenExpired"

#define LEAD_SOURCE_PARAMETER @"LeadSource"
#define POSTAL_CODE_PARAMETER @"PostalCode"


#define CLOSE_DATE_PARAMETER @"CloseDate"
#define EXPECTED_REVENUE_PARAMETER @"ExpectedRevenue"
#define STAGE_NAME_PARAMETER @"StageName"
#define NEXT_STEP_PARAMETER @"NextStep"

#define IS_CLOSED_PARAMETER @"IsClosed"
#define IS_DELETED_PARAMETER @"IsDeleted"
#define IS_PRIVATE_PARAEMETER @"IsPrivate"
#define IS_WON_PARAMETER @"IsWon"
#define TOTAL_OPP_QUANTITY @"TotalOpportunityQuantity"
#define CLOSED_STATUS @"Closed"
#define DELETED_STATUS @"Deleted"
#define PRIVATE_STATUS @"Private"
#define WON_STATUS @"Won"

#define DEFAULT_USER_ICON @"dashboard_user.png"
#define BODY_PARAMETER @"Body"
#define PARENT_ID_PARAMETER @"ParentId"

#define ERRORS_PARAMETER @"errors"
#define SUCCESS_PARAMETER @"success"

#define DURATION_IN_MINUTES_PARAMETER @"DurationInMinutes"

#define WHAT_ID_PARAMETER @"WhatId"
#define WHO_ID_PARAMETER @"WhoId"
#define ZIP_PARAMETER @"Zip"

